Homework 3: fragments
Kochenkov/AndroidApp-AnimeCatalog pull request #3
Opened 2021-02-09 10:34 UTC by Kochenkov

https://user-images.githubusercontent.com/38836366/107351195-5fa59000-6adb-11eb-81e7-6490150bca95.mp4

2021-02-16 22:39 UTC, baidala requested changes
отличный проект. надо исправить небольшие замечания

2021-02-16 22:39 UTC, baidala commented on app/src/main/java/com/vkochenkov/filmscatalog/MainActivity.kt
> +        bottomNavView = findViewById(R.id.bottom_nav_view)
инициализацию bottomNavView и лиснер  лучше вынести в отдельный метод

2021-02-16 22:39 UTC, baidala commented on app/src/main/res/layout/fragment_film_info.xml
> +            <androidx.appcompat.widget.Toolbar
название фильма перекрывает постер и на темном постере название нечитаемо

2021-02-17 14:51 UTC, Kochenkov commented on app/src/main/res/layout/fragment_film_info.xml
> +            <androidx.appcompat.widget.Toolbar
спасибо, поправил. Сделал отдельный стиль для текста в раскрытом тулбаре

2021-02-17 14:51 UTC, Kochenkov commented on app/src/main/java/com/vkochenkov/filmscatalog/MainActivity.kt
> +        bottomNavView = findViewById(R.id.bottom_nav_view)
сделано

2021-02-17 21:43 UTC, merged