Homework 4: mvvm architecture + rest api + room storage
Kochenkov/AndroidApp-AnimeCatalog pull request #4
Opened 2021-03-05 14:53 UTC by Kochenkov

https://user-images.githubusercontent.com/38836366/110131837-a1c0a980-7ddb-11eb-8edc-8f7636f62770.mp4

2021-03-13 14:28 UTC, baidala requested changes
вобщем проект хороший. код  структурирован и разбит на логические методы. но надо исправить моменты с передачей view во viewModel

2021-03-13 14:28 UTC, baidala commented on app/src/main/java/com/vkochenkov/filmscatalog/model/Repository.kt
> +    val appContext by lazy {App.instance?.applicationContext!!}
я бы не рекомендовал здесь хранить контекст. вместо этого вы можете создать специальный класс Result и передавать его с параметрами . например: 
`sealed class Result<out T> {

    data class Success<out T>(val data: T?) : Result<T>()
    data class Error<out T>(val data: T?, val message: String?) : Result<T>()

    override fun toString(): String {
        return when (this) {
            is Success<*> -> "Success[data=$data]"
            is Error<*> -> "Error[exception=$message]"
        }
    }

    companion object {
        fun <T : Any> success(data: T): Success<T> {
            return Success(data)
        }

        fun <T> success(): Success<T> {
            return Success(null)
        }

        fun <T> error(message: String, data: T? = null): Error<T> {
            return Error(data, message)
        }
    }
}`

2021-03-13 14:28 UTC, baidala commented on app/src/main/java/com/vkochenkov/filmscatalog/model/Repository.kt
> +                    callback.onSuccess(filmsListFromApi)
можно передавать свой класс  Result.success(list)

2021-03-13 14:28 UTC, baidala commented on app/src/main/java/com/vkochenkov/filmscatalog/model/Repository.kt
> +                    callback.onFailure(appContext.getString(R.string.api_error_server_str) + " " + response.code())
можно передавать свой класс  Result.error(response.code())

2021-03-13 14:28 UTC, baidala commented on app/src/main/java/com/vkochenkov/filmscatalog/model/Repository.kt
> +                    for (i in response.body()!!.data.indices) {
этот цикд можно переписать:
`response.body()?.data?.forEach {
                        filmsListFromApi.add(
                                Film(
                                        it.attributes.serverName,
                                        it.attributes.title,
                                        it.attributes.description,
                                        it.attributes.posterImage.original,
                                        it.attributes.startDate,
                                        it.attributes.ageRating,
                                        it.attributes.episodeCount,
                                        it.attributes.averageRating,
                                        false
                                )
                        )
                    }`

2021-03-13 14:28 UTC, baidala commented on app/src/main/java/com/vkochenkov/filmscatalog/viewmodel/FilmsViewModel.kt
> +    fun getFilmsWithPaging(progressBar: ProgressBar, shouldIncrementPageCount: Boolean = true) {
передавать сюда елементы вью - не лучшая идея. вью может умереть раньше  вьюмодели. вы можете менять прогресс бар во фрагменте. а когда получите во фрагменте новые данные - спрячите прогрессбар.
либо создать свой  sealed class Status.  и еммитить для фрагмента разные статусы (loading/success/error)

2021-03-13 14:28 UTC, baidala commented on app/src/main/java/com/vkochenkov/filmscatalog/viewmodel/FavouriteFilmsViewModel.kt
> +    var mutableFavouritesLiveData = MutableLiveData<List<Film>>()
private var mutableFavouritesLiveData = MutableLiveData<List<Film>>()
наружу отдавать только на чтение

2021-03-13 14:28 UTC, baidala commented on app/src/main/java/com/vkochenkov/filmscatalog/viewmodel/FilmsViewModel.kt
> +    fun getFilmsWithPaging(swipeRefresh: SwipeRefreshLayout) {
аналогично - вьюмодель не должна знать про елементы вью. это не ее задача. и это нарушение паттерна mvvm

2021-03-15 07:48 UTC, Kochenkov commented on app/src/main/java/com/vkochenkov/filmscatalog/model/Repository.kt
> +                    for (i in response.body()!!.data.indices) {
fixed

2021-03-15 07:49 UTC, Kochenkov commented on app/src/main/java/com/vkochenkov/filmscatalog/viewmodel/FavouriteFilmsViewModel.kt
> +    var mutableFavouritesLiveData = MutableLiveData<List<Film>>()
fixed

2021-03-15 10:35 UTC, Kochenkov commented on app/src/main/java/com/vkochenkov/filmscatalog/model/Repository.kt
> +    val appContext by lazy {App.instance?.applicationContext!!}
Контекст тут нужен для того, что бы вытаскивать строки из ресурсов, для того что бы показывать ошибку в зависимости от языка.
Если честно, не совсем понял предложенную концепцию.

2021-03-15 10:35 UTC, Kochenkov commented on app/src/main/java/com/vkochenkov/filmscatalog/viewmodel/FilmsViewModel.kt
> +    fun getFilmsWithPaging(progressBar: ProgressBar, shouldIncrementPageCount: Boolean = true) {
спасибо, исправил, воспользовался первым вариантом.

2021-03-15 10:35 UTC, Kochenkov commented on app/src/main/java/com/vkochenkov/filmscatalog/viewmodel/FilmsViewModel.kt
> +    fun getFilmsWithPaging(swipeRefresh: SwipeRefreshLayout) {
fixed

2021-03-19 20:32 UTC, baidala commented on app/src/main/java/com/vkochenkov/filmscatalog/model/Repository.kt
> +    val appContext by lazy {App.instance?.applicationContext!!}
отображать текст - это задача фрагмента (вьюмодели). в репозитории конктекст не нужен. sealed class Result - это просто вариант обертки над данными. по типу класса (Success/Error) можно разу понять  каков результат. и этот результат можно передавать через один поток  liveData<Result>

2021-03-19 20:43 UTC, baidala approved these changes
теперь все отлично. можно мержить

2021-03-19 20:52 UTC, baidala approved these changes

2021-03-19 20:52 UTC, baidala commented on app/src/main/java/com/vkochenkov/filmscatalog/view/fragments/FilmsListFragment.kt
> +        initOnDataChangeObserver()
это лучше вызывать в onViewCreated()

2021-03-20 07:25 UTC, merged